### ISSUE TITLE
iOS create plugin hang

### ISSUE THREAD

**Issue by alperozisik** [SmartfaceIO/smfc#1] opened 2015-10-09 08:52 UTC
@serkanserttop, create plugin that I have committed  bad9cf6d0faf08568f8fbb2a248bd929286d0461 contains the code that I have created.
At the end of the operation I call callback method. The process hangs at that point.

**Comment by serkanserttop** [comment] 2015-10-09 09:37
In debug mode, the process may not end until you kill it.
This works in normal call for me, please close the issue if the issue is resolved for you as well.

**Closed** 2015-10-10 09:31 UTC
